apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-2xa2
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0023-tenant/tkrw-pr712-0075-0023-app/devfile-sample-2xa2@sha256:1c88c1c57ca378b907fec54eec503d363a70eb9f5699e73fc1ef5284243c2b7a
        name: my-nodejs
        resources: {}
status: {}
